# Generated by Django 5.0.6 on 2024-06-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributos', models.CharField(max_length=255)),
                ('tablas', models.CharField(max_length=255)),
                ('condiciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
